[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/framework-info"]
  
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

[functions."*"]
  timeout = 60