[build]
  command = "npm run build"
  publish = ".next"  # For standard Next.js builds
  # OR if using static export:
  # publish = "out"  # Only if you're using `next export`

[functions]
  directory = ".next/_next/static/chunks/app/api"
  node_bundler = "esbuild"

  [functions.settings]
    timeout = 60