[build]
  command = "npm run build"
  publish = "out"  # or your Next.js output directory

[functions]
  directory = ".next/serverless/pages/api"  # For Next.js API routes
  node_bundler = "esbuild"  # or "nft" for more control

  [functions.settings]
    # Timeout in seconds (max 30 for starter plans)
    timeout = 30  

    # If you need to include specific node modules
    external_node_modules = ["@langchain/core", "mongodb"]